name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Login to LeetCode and get tokens
        run: python3 login_script.py
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}

      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ env.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ env.LEETCODE_SESSION }}
          destination-folder: my-folder
          verbose: true
          commit-header: "[LeetCode Sync]"
